name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Zola
        run: |
          sudo snap install --edge zola
      - name: Run Zola
        run: |
          zola build
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy to Website
        run: |
          rsync -avx --exclude .DS_Store public ${{ secrets.TARGET }}
